### ISSUE TITLE
(node:17124) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'displayAvatarURL' of undefined

### ISSUE THREAD

**Issue by Oxadeum** [Mr-KayJayDee/discord-image-generation#6] opened 2020-08-26 09:29 UTC
Hello ! ^^

I have a problem with my code
The error is in the title

My code : 

[Code](https://sourceb.in/fc028dc1cf)

**Comment by Mr-KayJayDee** [comment] 2020-08-26 09:32
Dupe of [Issue 5](https://github.com/Mr-KayJayDee/discord-image-generation/issues/5)

**Closed by Mr-KayJayDee** 2020-08-26 09:32 UTC
